#  This file is part of RADAR.
#  Copyright (C) 2019 Cole Daubenspeck
#
#  RADAR is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  RADAR is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RADAR.  If not, see <https://www.gnu.org/licenses/>.

[web_server]
listen_address = "0.0.0.0"
port = 1794

# Uncomment out below and include path to public and private keys if you want to run HTTPS endpoints (recommended for non-dev use)
#[certificates]
#public_key = "server.crt"
#private_key = "server.key"

[database]
host = "localhost"
port = 27017
username = "root"
password = "R4d4rD4t4b4s3"
timeout = 2000
